//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SztucznaIntCw.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class meals
    {
        public int id_meal { get; set; }
        public Nullable<int> id_product { get; set; }
        public bool first_meal { get; set; }
        public bool second_meal { get; set; }
        public bool third_meal { get; set; }
        public bool fourth_meal { get; set; }
        public bool fifth_meal { get; set; }
    
        public virtual products products { get; set; }
    }
}
